spring.application.name=LearningRestApi

#Port configuration
server.port=8081

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true